name: DCO

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_dco:
    name: Check DCO
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Run dco-check
        uses: christophebedard/dco-check@master
        with:
            python-version: ${{ matrix.python-version }}
            args: '--verbose'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
